version: 2.1
orbs:
  codecov: codecov/codecov@1.2.3
jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: npm run test
  coverage:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: npm test -- --coverage
      - store_artifacts:
          path: coverage
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Build the app"
          command: npm build
  codecov:
    docker: 
      - image: cimg/node:15.1
    steps:
      - checkout
      - run: npm test -- --coverage
      - codecov/upload:
          file: '/coverage/'
workflows:
  version: 2
  orb-free-workflow:
    jobs:
      - test
      - coverage
      - build
      - codecov:
          requires:
            - coverage
